### ISSUE TITLE
v1.0.4 can not find SharedPreference files on Windows 10, but v1.0.3 ok

### ISSUE THREAD

**Issue by Honghe** [shchurov/SharedPreferences-Editor-Plugin#1]
# Environment
- Android Studio 2.2.1
- Android 5.1.1 (Xiaomi) not root.

on Windows 10
v1.0.4 can not find SharedPreference files on Windows 10, but v1.0.3 ok.

on Ubuntu 14.04 : the error message is:

```
SharedPreferencesEditor: Error while creating temporary directories
```

**Comment by mikehodz** [comment]
Hi, @Honghe thanks for your feedback! 
I'm going to publish a new version today with a more verbose error explanation, may I ask you to update the plugin and attach error logs here?

**Comment by mikehodz** [comment]
@Honghe v1.05 is there

**Comment by Honghe** [comment]
v1.0.5 on Ubuntu 14.04 error message:

```
CreateDirectoriesException
           Error while creating temporary directories
           I would really appreciate if you file this issue with the details here: https://github.com/shchurov/SharedPreferences-Editor-Plugin


```

**Comment by mikehodz** [comment]
@Honghe, so there's no error stacktrace in the bottom or any other details?

**Comment by Honghe** [comment]
Nope

**Comment by mikehodz** [comment]
@Honghe, thanks, I will check it

**Comment by Honghe** [comment]
Sorry. Android Studio hides the error detail default on Ubuntu. And the error comes from `adb` in specific situation, not your plugin. Thanks for your detail error message.

Brief Summary, at least, the following 2 situations will raise adb error:
- if the `chmod` of the `/data/data` is changed, then `run-as xxx` will raise `Package 'xxx' has corrupt installation`, even through the package is in debug mode.
- if the debugable apk is install in A computer, then `run-as xxx` in another computer connected with the phone, the fail too. [updated 2016.10.12, this situation is ok.]

Bellow is the error detail:

```
Error while parsing SharedPreferences file
I would really appreciate if you file this issue with the details here: https://github.com/shchurov/SharedPreferences-Editor-Plugin

Details: 
Command: adb -s 22da671e shell echo $EXTERNAL_STORAGE
/storage/sdcard0

Command: adb -s 22da671e shell mkdir -p /storage/sdcard0/prefs_editor/normal


Command: adb -s 22da671e shell mkdir -p /storage/sdcard0/prefs_editor/unified


Command: adb -s 22da671e shell rm -rf /storage/sdcard0/prefs_editor/normal/*


Command: adb -s 22da671e shell rm -rf /storage/sdcard0/prefs_editor/unified/*


Command: adb -s 22da671e shell run-as top.honhe.demo_imei chmod -R 777 /data/data/top.honhe.demo_imei/shared_prefs/
run-as: Package 'top.honhe.demo_imei' has corrupt installation

Command: adb -s 22da671e shell cp /data/data/top.honhe.demo_imei/shared_prefs/* /storage/sdcard0/prefs_editor/normal
cp: /data/data/top.honhe.demo_imei/shared_prefs/*: No such file or directory

Command: adb -s 22da671e shell for f in /storage/sdcard0/prefs_editor/normal/*; do echo $f; done
/storage/sdcard0/prefs_editor/normal/*

Command: adb -s 22da671e shell mv /storage/sdcard0/prefs_editor/normal/* /storage/sdcard0/prefs_editor/unified/pref0.xml
mv: rename /storage/sdcard0/prefs_editor/normal/* to /storage/sdcard0/prefs_editor/unified/pref0.xml: No such file or directory

Command: adb pull /storage/sdcard0/prefs_editor/unified C:\Users\123\AppData\Local\Temp\3885993078090927208
pull: building file list...
/storage/sdcard0/prefs_editor/unified/: 1 file pulled. 0 files skipped

com.github.shchurov.prefseditor.helpers.exceptions.ParsePreferencesException: Error while parsing SharedPreferences file
    at com.github.shchurov.prefseditor.helpers.PreferencesParser.parse(PreferencesParser.java:28)
    at com.github.shchurov.prefseditor.OpenEditorAction.actionPerformed(OpenEditorAction.java:57)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:191)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:312)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
    at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:110)
    at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:513)
    at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
    at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
    at java.awt.Component.processMouseEvent(Component.java:6533)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6298)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4889)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2746)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.io.FileNotFoundException: C:\Users\123\AppData\Local\Temp\3885993078090927208\unified\pref0.xml (The system cannot find the file specified)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at java.io.FileInputStream.<init>(FileInputStream.java:93)
    at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
    at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
    at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
    at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
    at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
    at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
    at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
    at com.github.shchurov.prefseditor.helpers.PreferencesParser.buildDocument(PreferencesParser.java:34)
    at com.github.shchurov.prefseditor.helpers.PreferencesParser.parse(PreferencesParser.java:25)
    ... 45 more
```

**Comment by mikehodz** [comment]
@Honghe, do you mean manual `chmod` change of `/data/data`?
I will check the second issue tomorrow with another pc.
Anyway, many thanks for your investigation!

**Comment by Honghe** [comment]
= =! the second issue is ok, I make a mistake.
The detail error in Ubuntu 14.04 is as follow. 
it seems odd. Cause, I can run `adb` in Ubuntu shell normally. And I can run `adb -s <device id> shell mkdir -p /storage/sdcard0/prefs_editor/normal` manually.

```
Error while creating temporary directories
I would really appreciate if you file this issue with the details here: https://github.com/shchurov/SharedPreferences-Editor-Plugin

com.github.shchurov.prefseditor.helpers.exceptions.CreateDirectoriesException: Error while creating temporary directories
    at com.github.shchurov.prefseditor.helpers.DirectoriesCreator.lambda$createDirectories$0(DirectoriesCreator.java:32)
    at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:198)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:357)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.application.impl.ApplicationImpl$13$1.run(ApplicationImpl.java:633)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.github.shchurov.prefseditor.helpers.exceptions.ExecuteAdbCommandException: java.io.IOException: Cannot run program "adb": error=2, No such file or directory
    at com.github.shchurov.prefseditor.helpers.adb.AdbCommandExecutor.execute(AdbCommandExecutor.java:25)
    at com.github.shchurov.prefseditor.helpers.adb.AdbShellHelper.exec(AdbShellHelper.java:19)
    at com.github.shchurov.prefseditor.helpers.adb.AdbShellHelper.getSdCardPath(AdbShellHelper.java:15)
    at com.github.shchurov.prefseditor.helpers.DirectoriesCreator.performCreateDirectories(DirectoriesCreator.java:38)
    at com.github.shchurov.prefseditor.helpers.DirectoriesCreator.lambda$createDirectories$0(DirectoriesCreator.java:30)
    ... 15 more
Caused by: java.io.IOException: Cannot run program "adb": error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    at java.lang.Runtime.exec(Runtime.java:620)
    at java.lang.Runtime.exec(Runtime.java:450)
    at java.lang.Runtime.exec(Runtime.java:347)
    at com.github.shchurov.prefseditor.helpers.adb.AdbCommandExecutor.execute(AdbCommandExecutor.java:13)
    ... 19 more
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
    at java.lang.ProcessImpl.start(ProcessImpl.java:134)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    ... 23 more

```

**Comment by mikehodz** [comment]
@Honghe, so it works for you on Windows 10 but doesn't work on Ubuntu 14.04?

**Comment by Honghe** [comment]
Yes.

**Comment by mikehodz** [comment]
@Honghe, I will check it on Ubuntu, thanks!

**Comment by mikehodz** [comment]
@Honghe, btw do you have x86 or x64 Ubuntu?
Also I just realized that not all users have adb in their environment variables. I would assume you have it there, can you confirm?

**Comment by Honghe** [comment]
Ubuntu x64.
`have adb in their environment variables` What variables does this plugin needed?

I have set `ANDROID_HOME      ANDROID_NDK       ANDROID_NDK_HOME  ANDROID_SDK` and other plugins, such as `Adb Commander` and `Adb IDEA`, can work fine. Also I can run `adb` on `zsh` and `bash`.

And, how to print the way this plugin searchs adb? Maybe this can be helpful.

**Comment by mikehodz** [comment]
@Honghe, I've released v1.06 yesterday it gets adb path from idea and uses it explicitly. So you can try to update and check the commands log again

**Comment by Honghe** [comment]
v1.0.6
This version can find `adb`. But meet another problem, odd too.
The return of `echo $EXTERNAL_STORAGE` lost some char.

```
echo $EXTERNAL_STORAGE
/storage/emulated/legac
```

But The `AdbCommander` plugin and I run `adb $EXTERNAL_STORAGE` manually both return the whole path, as the follow pic:
![screenshot from 2016-10-13 16 00 56](https://cloud.githubusercontent.com/assets/1092722/19341098/9cd37862-915e-11e6-94b3-6fe1dc054692.png)

Error detail message as follow:

```
Error while pulling SharedPreferences files
I would really appreciate if you file this issue with the details here: https://github.com/shchurov/SharedPreferences-Editor-Plugin

Details: 
Command: /home/honhe/Android/Sdk/platform-tools/adb -s a03eb263 shell echo $EXTERNAL_STORAGE
/storage/emulated/legac

Command: /home/honhe/Android/Sdk/platform-tools/adb -s a03eb263 shell mkdir -p /storage/emulated/legac/prefs_editor/normal
mkdir failed for /storage/emulated/legac/, Read-only file syste

Command: /home/honhe/Android/Sdk/platform-tools/adb -s a03eb263 shell mkdir -p /storage/emulated/legac/prefs_editor/unified
mkdir failed for /storage/emulated/legac/, Read-only file syste

Command: /home/honhe/Android/Sdk/platform-tools/adb -s a03eb263 shell rm -rf /storage/emulated/legac/prefs_editor/normal/*


Command: /home/honhe/Android/Sdk/platform-tools/adb -s a03eb263 shell rm -rf /storage/emulated/legac/prefs_editor/unified/*


Command: /home/honhe/Android/Sdk/platform-tools/adb -s a03eb263 shell run-as top.honhe.ex chmod -R 777 /data/data/top.honhe.ex/shared_prefs/


Command: /home/honhe/Android/Sdk/platform-tools/adb -s a03eb263 shell cp /data/data/top.honhe.ex/shared_prefs/* /storage/emulated/legac/prefs_editor/normal
cp: /storage/emulated/legac/prefs_editor/normal: No such file or director

Command: /home/honhe/Android/Sdk/platform-tools/adb -s a03eb263 shell for f in /storage/emulated/legac/prefs_editor/normal/*; do echo $f; done
/storage/emulated/legac/prefs_editor/normal/

Command: /home/honhe/Android/Sdk/platform-tools/adb -s a03eb263 shell mv /storage/emulated/legac/prefs_editor/normal/normal /storage/emulated/legac/prefs_editor/unified/pref0.xml
mv: rename /storage/emulated/legac/prefs_editor/normal/normal to /storage/emulated/legac/prefs_editor/unified/pref0.xml: No such file or director

com.github.shchurov.prefseditor.helpers.exceptions.PullFilesException: Error while pulling SharedPreferences files
    at com.github.shchurov.prefseditor.helpers.FilesPuller.lambda$pullFiles$1(FilesPuller.java:33)
    at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:198)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:357)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.application.impl.ApplicationImpl$13$1.run(ApplicationImpl.java:633)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.github.shchurov.prefseditor.helpers.exceptions.ExecuteAdbCommandException: java.io.IOException: Cannot run program "adb": error=2, No such file or directory
    at com.github.shchurov.prefseditor.helpers.adb.AdbCommandExecutor.execute(AdbCommandExecutor.java:25)
    at com.github.shchurov.prefseditor.helpers.adb.AdbShellHelper.exec(AdbShellHelper.java:19)
    at com.github.shchurov.prefseditor.helpers.adb.AdbShellHelper.pullFile(AdbShellHelper.java:65)
    at com.github.shchurov.prefseditor.helpers.FilesPuller.performPullFiles(FilesPuller.java:45)
    at com.github.shchurov.prefseditor.helpers.FilesPuller.lambda$pullFiles$1(FilesPuller.java:31)
    ... 15 more
Caused by: java.io.IOException: Cannot run program "adb": error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    at java.lang.Runtime.exec(Runtime.java:620)
    at java.lang.Runtime.exec(Runtime.java:450)
    at java.lang.Runtime.exec(Runtime.java:347)
    at com.github.shchurov.prefseditor.helpers.adb.AdbCommandExecutor.execute(AdbCommandExecutor.java:13)
    ... 19 more
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
    at java.lang.ProcessImpl.start(ProcessImpl.java:134)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    ... 23 more
```

**Comment by mikehodz** [comment]
@Honghe, Ok, good that it finds adb now, looks like it removes that char here:
https://github.com/shchurov/SharedPreferences-Editor-Plugin/blob/master/src/main/java/com/github/shchurov/prefseditor/helpers/adb/AdbCommandExecutor.java#L21

I will try to do it in a more intelligent way

**Comment by mikehodz** [comment]
@Honghe, v1.07 is released, could you check it again?

**Comment by Honghe** [comment]
v1.0.7 error message:

```
Error while pulling SharedPreferences files
I would really appreciate if you file this issue with the details here: https://github.com/shchurov/SharedPreferences-Editor-Plugin

Details: 
Command: /home/honhe/Android/Sdk/platform-tools/adb -s a03eb263 shell echo $EXTERNAL_STORAGE
/storage/emulated/legacy

Command: /home/honhe/Android/Sdk/platform-tools/adb -s a03eb263 shell mkdir -p /storage/emulated/legacy/prefs_editor/normal


Command: /home/honhe/Android/Sdk/platform-tools/adb -s a03eb263 shell mkdir -p /storage/emulated/legacy/prefs_editor/unified


Command: /home/honhe/Android/Sdk/platform-tools/adb -s a03eb263 shell rm -rf /storage/emulated/legacy/prefs_editor/normal/*


Command: /home/honhe/Android/Sdk/platform-tools/adb -s a03eb263 shell rm -rf /storage/emulated/legacy/prefs_editor/unified/*


Command: /home/honhe/Android/Sdk/platform-tools/adb -s a03eb263 shell run-as top.honhe.ex chmod -R 777 /data/data/top.honhe.ex/shared_prefs/


Command: /home/honhe/Android/Sdk/platform-tools/adb -s a03eb263 shell cp /data/data/top.honhe.ex/shared_prefs/* /storage/emulated/legacy/prefs_editor/normal


Command: /home/honhe/Android/Sdk/platform-tools/adb -s a03eb263 shell for f in /storage/emulated/legacy/prefs_editor/normal/*; do echo $f; done
/storage/emulated/legacy/prefs_editor/normal/main.xml

Command: /home/honhe/Android/Sdk/platform-tools/adb -s a03eb263 shell mv /storage/emulated/legacy/prefs_editor/normal/main.xml /storage/emulated/legacy/prefs_editor/unified/pref0.xml


com.github.shchurov.prefseditor.helpers.exceptions.PullFilesException: Error while pulling SharedPreferences files
    at com.github.shchurov.prefseditor.helpers.FilesPuller.lambda$pullFiles$1(FilesPuller.java:30)
    at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:198)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:357)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.application.impl.ApplicationImpl$13$1.run(ApplicationImpl.java:633)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.github.shchurov.prefseditor.helpers.exceptions.ExecuteAdbCommandException: java.io.IOException: Cannot run program "adb": error=2, No such file or directory
    at com.github.shchurov.prefseditor.helpers.adb.AdbCommandExecutor.execute(AdbCommandExecutor.java:24)
    at com.github.shchurov.prefseditor.helpers.adb.AdbShellHelper.exec(AdbShellHelper.java:19)
    at com.github.shchurov.prefseditor.helpers.adb.AdbShellHelper.pullFile(AdbShellHelper.java:65)
    at com.github.shchurov.prefseditor.helpers.FilesPuller.performPullFiles(FilesPuller.java:45)
    at com.github.shchurov.prefseditor.helpers.FilesPuller.lambda$pullFiles$1(FilesPuller.java:28)
    ... 15 more
Caused by: java.io.IOException: Cannot run program "adb": error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    at java.lang.Runtime.exec(Runtime.java:620)
    at java.lang.Runtime.exec(Runtime.java:450)
    at java.lang.Runtime.exec(Runtime.java:347)
    at com.github.shchurov.prefseditor.helpers.adb.AdbCommandExecutor.execute(AdbCommandExecutor.java:13)
    ... 19 more
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
    at java.lang.ProcessImpl.start(ProcessImpl.java:134)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    ... 23 more
```

**Comment by mikehodz** [comment]
@Honghe, great, we're very close
Now the problem is here:
https://github.com/shchurov/SharedPreferences-Editor-Plugin/blob/master/src/main/java/com/github/shchurov/prefseditor/helpers/adb/AdbShellHelper.java#L65
It should also use explicit adb path, will fix it

**Comment by mikehodz** [comment]
@Honghe, could you check v1.08?

**Comment by Honghe** [comment]
Windows 10 is ok, I will check int on Ubuntu 14.04 tomorrow.

**Comment by Honghe** [comment]
v1.08 works well on Ubuntu 14.04 now.

**Comment by mikehodz** [comment]
@Honghe, great! Thanks for cooperation!
